# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flylo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_number', models.CharField(max_length=4, null=True)),
                ('seats_bussines_id', models.CharField(max_length=100, null=True)),
                ('seats_economic_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.CharField(max_length=3, null=True)),
                ('offer_categories', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='nbussiness_free',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='neconomic_free',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='seats_bussines_free',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='seats_economic_free',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flylo.Aircraft'),
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimated_time_arrival',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='estimated_time_departure',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='location_arrival',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='location_departure',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ManyToManyField(to='flylo.Airline'),
        ),
    ]
