# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0005_auto_20170601_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.FloatField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
